version = 0.1

[default.deploy.parameters]
stack_name = "lambda-slog"
resolve_s3 = true
s3_prefix = "lambda-slog"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" LogLevel=\"INFO\""
image_repositories = []
